import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../services/api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {


  // hold error message
  eMsg = ""

  msg = ""


  // Login form -reactive form
  loginForm = this.fb.group({
    // validators used
    acno: ['', [Validators.required, Validators.pattern('[0-9]*')]],
    pswd: ['', [Validators.required, Validators.pattern('[a-z A-Z 0-9]*')]]
  })

  constructor(private fb: FormBuilder, private api: ApiService, private router: Router) { }

  ngOnInit(): void {
  }



  login() {

    // complete Form validation
    if (this.loginForm.valid) {
      let acno = this.loginForm.value.acno
      let pswd = this.loginForm.value.pswd
      // Asynchronous function call login is a api service function
      this.api.login(acno, pswd)
        .subscribe(
    // response 200
          (result: any) => {
            console.log(result);

            // set welcome user
            localStorage.setItem("username", result.username)

            // to get token generated by backend and current acc no.

            localStorage.setItem("token", result.token)
            localStorage.setItem("currentAcno", result.currentAcno)


            // alert(result.message)
            this.msg = result.message

            // redirecting to another page

            setTimeout(() => {
              this.router.navigateByUrl('dashboard')
            }, 2000);


          },
          // response 4XX
          (result: any) => {
            this.eMsg = result.error.message
            // alert(result.error.message)

          }
        )

    }
    else {
      alert('Invalid Form')
    }



  }

}
